harness_platform_account_id = "Io9SR1H7TtGBq9LVyJVB2w"
organization_prefix         = "cristian-lab-devsecops-org"

harness_platform_organizations = {
  "cristian-lab-devsecops-org" = {
    enable      = true
    description = "Organization generated by terraform harness provider"
  }
}
