locals {
  cristiab_lab_org_connectors = {
    github = {
      crizstian-lab = {
        enable          = true
        description     = "Connector generated by terraform harness provider"
        connection_type = "Account"
        url             = "https://github.com/Crizstian"
        validation_repo = "harness-as-code"
        org_id          = module.bootstrap_harness.organization[var.cristian_lab_org_projects.organization_name].org_id
        credentials = {
          http = {
            username  = "crizstian"
            token_ref = var.harness_connectors_crizstian_github_token
          }
        }
      }
    }
    # docker = {
    #   crizstian-lab = {
    #     enable      = false
    #     description = "Connector generated by terraform harness provider"
    #     tags        = ["local:environment"]
    #     # delegate_selectors = ["local-environment"]
    #     org_id = ""
    #     type   = "DockerHub"
    #     url    = "https://registry.hub.docker.com/v1/"
    #     credentials = {
    #       username = "crizstian"
    #       # password_ref = var.harness_connectors_crizstian_docker_token
    #     }
    #   }
    # }
  }
}
