variable "cristian_lab_orgs" {
  default = {
    "cristian-lab-bcp-org" = {
      enable      = true
      description = "Organization generated by terraform harness provider"
    }
    "cristian-lab-cinemas-org" = {
      enable      = true
      description = "Organization generated by terraform harness provider"
    }
  }
}
