locals {
  cristian-delegate-tf = "cristian-delegate-tf"
  cristian_account_delegates = {
    k8s = {
      "${local.cristian-delegate-tf}" = {
        enable                 = true
        description            = "Delegate deployed and generated by terraform harness provider"
        size                   = "SMALL"
        tags                   = ["${local.cristian-delegate-tf}"]
        clusterPermissionType  = "CLUSTER_ADMIN"
        customClusterNamespace = "harness-delegate-ng"
      }
    }
  }
}
