variable "harness_platform_account_id" {
  sensitive = true
}
variable "harness_platform_api_key" {
  sensitive = true
}

variable "harness_platform_projects" {
  default = {
    cristian-labs-org = {
      enable      = true
      description = "Organization generated by terraform harness provider"
      projects = {
        "Cinemas Microservice" = {
          enable      = true
          description = "Project generated by terraform harness provider"
        }
      }
    }
  }
}
