locals {
  cristian_account_secrets = {
    cristian_account_platform_api_key = {
      secret      = var.harness_platform_api_key
      description = "Secret generated by terraform harness provider"
    }
    cristian_account_platform_account_id = {
      secret      = var.harness_platform_account_id
      description = "Secret generated by terraform harness provider"
    }
  }
}
