locals {
  cristiab_lab_org_delegates = {
    k8s = {
      cristian-gke-tf = {
        enable                 = true
        description            = "Delegate deployed and generated by terraform harness provider"
        size                   = "SMALL"
        tags                   = ["gcp-environment", "cr-tf"]
        clusterPermissionType  = "CLUSTER_ADMIN"
        customClusterNamespace = "harness-delegate-ng"
        org_id                 = module.bootstrap_harness_account.organization[var.cristian_lab_org_projects.organization_name].org_id
      }
    }
  }
}
