variable "cristian_lab_orgs" {
  default = {
    "cristian-lab-bcp-org" = {
      enable      = true
      description = "Organization generated by terraform harness provider"
    }
    "cristian-lab-cinemas-org" = {
      enable      = true
      description = "Organization generated by terraform harness provider"
    }
  }
}


# projects = {
#   "Harness Cinemas Seed" = {
#     enable      = true
#     description = "Project generated by terraform harness provider"
#   }
#   "Harness BCP Seed" = {
#     enable      = true
#     description = "Project generated by terraform harness provider"
#   }
#   "Harness Italika Seed" = {
#     enable      = true
#     description = "Project generated by terraform harness provider"
#   }
# }
