variable "cristian_lab_org_projects" {
  default = {
    enable      = true
    description = "Cristian Labs bootstrap - Organization generated by terraform harness provider"
    projects = {
      "Harness Cinemas Seed" = {
        enable      = true
        description = "Harness-TF Cinemas Bootstrap - Project generated by terraform harness provider"
      }
      "Harness Italika Seed" = {
        enable      = true
        description = "Harness-TF Cinemas Bootstrap - Project generated by terraform harness provider"
      }
    }
  }
}

locals {
  harness_platform_projects = tomap({
    "cristiab-lab-org" = var.cristian_lab_org_projects
  })
  harness_platform_connectors = merge(
    local.cristiab_lab_org_connectors
  )
  harness_platform_delegates = tomap({
    k8s = merge(local.cristiab_lab_org_delegates.k8s)
  })
  harness_platform_secrets = {
    harness_platform_api_key = {
      secret      = var.harness_platform_api_key
      org_id      = module.bootstrap_harness.project["Harness Cinemas Seed"].org_id
      project_id  = module.bootstrap_harness.project["Harness Cinemas Seed"].identifier
      description = "harness_platform_api_key"
    }
    harness_platform_account_id = {
      secret      = var.harness_platform_account_id
      org_id      = module.bootstrap_harness.project["Harness Cinemas Seed"].org_id
      project_id  = module.bootstrap_harness.project["Harness Cinemas Seed"].identifier
      description = "harness_platform_account_id"
    }
    harness_connectors_crizstian_github_token = {
      secret      = var.harness_connectors_crizstian_github_token
      org_id      = module.bootstrap_harness.project["Harness Cinemas Seed"].org_id
      project_id  = module.bootstrap_harness.project["Harness Cinemas Seed"].identifier
      description = "harness_connectors_crizstian_github_token"
    }
    harness_connectors_crizstian_docker_token = {
      secret      = var.harness_connectors_crizstian_docker_token
      org_id      = module.bootstrap_harness.project["Harness Cinemas Seed"].org_id
      project_id  = module.bootstrap_harness.project["Harness Cinemas Seed"].identifier
      description = "harness_connectors_crizstian_docker_token"
    }
    harness_connectors_crizstian_artifactory_token = {
      secret      = var.harness_connectors_crizstian_artifactory_token
      org_id      = module.bootstrap_harness.project["Harness Cinemas Seed"].org_id
      project_id  = module.bootstrap_harness.project["Harness Cinemas Seed"].identifier
      description = "harness_connectors_crizstian_artifactory_token"
    }
  }

  cristiab_lab_org_delegates = {
    k8s = {
      cristian-gke-tf = {
        enable                 = true
        description            = "Delegate deployed and generated by terraform harness provider"
        size                   = "SMALL"
        tags                   = ["gcp-environment"]
        clusterPermissionType  = "CLUSTER_ADMIN"
        customClusterNamespace = "harness-delegate-ng"
        org_id                 = module.bootstrap_harness.organization["cristiab-lab-org"].org_id
      }
    }
  }

  cristiab_lab_org_connectors = {
    github = {
      crizstian-lab = {
        enable          = true
        description     = "Github Cinemas - Connector generated by terraform harness provider"
        connection_type = "Account"
        url             = "https://github.com/Crizstian"
        # delegate_selectors = ["local-environment"]
        validation_repo = "harness-as-code"
        org_id          = module.bootstrap_harness.project["Harness Cinemas Seed"].org_id
        project_id      = module.bootstrap_harness.project["Harness Cinemas Seed"].identifier
        credentials = {
          http = {
            username  = "crizstian"
            token_ref = var.harness_connectors_crizstian_github_token
          }
        }
      }
    }
    docker = {
      crizstian-lab = {
        enable      = false
        description = "Connector generated by terraform harness provider"
        tags        = ["local:environment"]
        # delegate_selectors = ["local-environment"]
        org_id = ""
        type   = "DockerHub"
        url    = "https://registry.hub.docker.com/v1/"
        credentials = {
          username = "crizstian"
          # password_ref = var.harness_connectors_crizstian_docker_token
        }
      }
    }
  }
}
