locals {
  cristian_secrets_org = {
    platform_api_key = {
      secret      = var.harness_platform_api_key
      org_id      = module.bootstrap_harness.organization[var.cristian_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    platform_account_id = {
      secret      = var.harness_platform_account_id
      org_id      = module.bootstrap_harness.organization[var.cristian_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    connector_crizstian_github_token = {
      secret      = var.harness_connector_crizstian_github_token
      org_id      = module.bootstrap_harness.organization[var.cristian_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    connector_crizstian_docker_token = {
      secret      = var.harness_connector_crizstian_docker_token
      org_id      = module.bootstrap_harness.organization[var.cristian_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
    connector_crizstian_artifactory_token = {
      secret      = var.harness_connector_crizstian_artifactory_token
      org_id      = module.bootstrap_harness.organization[var.cristian_lab_org_projects.organization_name].org_id
      description = "Secret generated by terraform harness provider"
    }
  }
}
