harness_opa_policies = {
  sto_required = {
    name        = "[DevSecOps Team] Stage - Security Module Required - Platform Policy"
    enable      = true
    description = "Policy Set generated by terraform harness provider"
    file        = "templates/devsecops/policies/platform/sto-required.rego"
    org_id      = "" # override policy level creation to account level
  }
}
